const Q_LINKS = {
  // Arrays & Two Pointers
  "Two Sum II (sorted)": { lc: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", gfg: "https://www.geeksforgeeks.org/problems/pair-with-given-sum-in-a-sorted-array4940/1" },
  "3Sum / 4Sum": { lc: "https://leetcode.com/problems/3sum/", gfg: "https://www.geeksforgeeks.org/problems/triplet-sum-in-array-1587115621/1" },
  "Container With Most Water": { lc: "https://leetcode.com/problems/container-with-most-water/", gfg: "https://www.geeksforgeeks.org/problems/container-with-most-water0535/1" },
  "Container with Most Water": { lc: "https://leetcode.com/problems/container-with-most-water/", gfg: "https://www.geeksforgeeks.org/problems/container-with-most-water0535/1" },
  "Valid Palindrome": { lc: "https://leetcode.com/problems/valid-palindrome/", gfg: "https://www.geeksforgeeks.org/problems/palindrome-string0817/1" },
  "Trapping Rain Water (2-ptr)": { lc: "https://leetcode.com/problems/trapping-rain-water/", gfg: "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1" },
  "Trapping Rain Water": { lc: "https://leetcode.com/problems/trapping-rain-water/", gfg: "https://www.geeksforgeeks.org/problems/trapping-rain-water-1587115621/1" },
  "Remove Duplicates from Sorted Array": { lc: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", gfg: "https://www.geeksforgeeks.org/problems/remove-duplicate-elements-from-sorted-array/1" },
  "Move Zeroes": { lc: "https://leetcode.com/problems/move-zeroes/", gfg: "https://www.geeksforgeeks.org/problems/move-all-zeroes-to-end-of-array0751/1" },
  "Linked List Cycle (Floyd's)": { lc: "https://leetcode.com/problems/linked-list-cycle/", gfg: "https://www.geeksforgeeks.org/problems/detect-loop-in-linked-list/1" },
  "Find the Duplicate Number": { lc: "https://leetcode.com/problems/find-the-duplicate-number/", gfg: "https://www.geeksforgeeks.org/problems/find-duplicates-in-an-array/1" },
  "Sort Colors (Dutch flag, 3-ptr)": { lc: "https://leetcode.com/problems/sort-colors/", gfg: "https://www.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1" },
  "Subarray Sum Equals K": { lc: "https://leetcode.com/problems/subarray-sum-equals-k/", gfg: "https://www.geeksforgeeks.org/problems/subarrays-with-sum-k/1" },
  "Range Sum Query - Immutable": { lc: "https://leetcode.com/problems/range-sum-query-immutable/", gfg: "https://www.geeksforgeeks.org/problems/sum-of-query-ii/1" },
  "Product of Array Except Self": { lc: "https://leetcode.com/problems/product-of-array-except-self/", gfg: "https://www.geeksforgeeks.org/problems/product-of-array-except-itself/1" },
  "Continuous Subarray Sum": { lc: "https://leetcode.com/problems/continuous-subarray-sum/", gfg: "https://www.geeksforgeeks.org/problems/continuously-increasing-subarrays/1" },
  "Car Pooling (difference array)": { lc: "https://leetcode.com/problems/car-pooling/", gfg: "https://www.geeksforgeeks.org/problems/car-pooling/1" },
  "Maximum Subarray": { lc: "https://leetcode.com/problems/maximum-subarray/", gfg: "https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1" },
  "Maximum Product Subarray": { lc: "https://leetcode.com/problems/maximum-product-subarray/", gfg: "https://www.geeksforgeeks.org/problems/maximum-product-subarray3604/1" },
  "Best Time to Buy and Sell Stock": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", gfg: "https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1" },
  "Maximum Sum Circular Subarray": { lc: "https://leetcode.com/problems/maximum-sum-circular-subarray/", gfg: "https://www.geeksforgeeks.org/problems/max-circular-subarray-sum-1587115620/1" },
  "Maximum Alternating Subsequence Sum": { lc: "https://leetcode.com/problems/maximum-alternating-subsequence-sum/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+alternating+subsequence+sum" },
  "First Missing Positive": { lc: "https://leetcode.com/problems/first-missing-positive/", gfg: "https://www.geeksforgeeks.org/problems/smallest-positive-missing-number-1587115621/1" },
  "Find All Numbers Disappeared in an Array": { lc: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/find-missing-and-additional-values2921/1" },
  "Set Matrix Zeroes": { lc: "https://leetcode.com/problems/set-matrix-zeroes/", gfg: "https://www.geeksforgeeks.org/problems/set-matrix-zeroes/1" },
  "Rotate Image": { lc: "https://leetcode.com/problems/rotate-image/", gfg: "https://www.geeksforgeeks.org/problems/rotate-by-90-degree-1587115621/1" },
  "Spiral Matrix": { lc: "https://leetcode.com/problems/spiral-matrix/", gfg: "https://www.geeksforgeeks.org/problems/spirally-traversing-a-matrix-1587115621/1" },
  "Game of Life": { lc: "https://leetcode.com/problems/game-of-life/", gfg: "https://www.geeksforgeeks.org/problems/game-of-life/1" },

  // Binary Search
  "Binary Search (basic)": { lc: "https://leetcode.com/problems/binary-search/", gfg: "https://www.geeksforgeeks.org/problems/binary-search-1587115620/1" },
  "First & Last Position (lower/upper bound)": { lc: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", gfg: "https://www.geeksforgeeks.org/problems/first-and-last-occurrences-of-x3116/1" },
  "Search Insert Position": { lc: "https://leetcode.com/problems/search-insert-position/", gfg: "https://www.geeksforgeeks.org/problems/search-insert-position-of-k-in-a-sorted-array/1" },
  "Find Peak Element": { lc: "https://leetcode.com/problems/find-peak-element/", gfg: "https://www.geeksforgeeks.org/problems/peak-element/1" },
  "Search in Rotated Sorted Array": { lc: "https://leetcode.com/problems/search-in-rotated-sorted-array/", gfg: "https://www.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1" },
  "Find Minimum in Rotated Sorted Array": { lc: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", gfg: "https://www.geeksforgeeks.org/problems/minimum-element-in-a-sorted-and-rotated-array3611/1" },
  "Search in Rotated Array II (dupes)": { lc: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", gfg: "https://www.geeksforgeeks.org/problems/search-in-a-rotated-array4618/1" },
  "Single Element in Sorted Array": { lc: "https://leetcode.com/problems/single-element-in-a-sorted-array/", gfg: "https://www.geeksforgeeks.org/problems/find-the-element-that-appears-once-in-sorted-array0624/1" },
  "Koko Eating Bananas": { lc: "https://leetcode.com/problems/koko-eating-bananas/", gfg: "https://www.geeksforgeeks.org/problems/koko-eating-bananas/1" },
  "Capacity to Ship Packages in D Days": { lc: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", gfg: "https://www.geeksforgeeks.org/problems/capacity-to-ship-packages-within-d-days/1" },
  "Split Array Largest Sum": { lc: "https://leetcode.com/problems/split-array-largest-sum/", gfg: "https://www.geeksforgeeks.org/problems/split-array-largest-sum--141634/1" },
  "Median of Two Sorted Arrays": { lc: "https://leetcode.com/problems/median-of-two-sorted-arrays/", gfg: "https://www.geeksforgeeks.org/problems/median-of-2-sorted-arrays-of-different-sizes/1" },
  "Minimize Max Distance to Gas Station": { lc: "https://leetcode.com/problems/minimize-max-distance-to-gas-station/", gfg: "https://www.geeksforgeeks.org/problems/minimize-max-distance-to-gas-station/1" },
  "Search a 2D Matrix": { lc: "https://leetcode.com/problems/search-a-2d-matrix/", gfg: "https://www.geeksforgeeks.org/problems/search-in-a-matrix-1587115621/1" },
  "Search a 2D Matrix II": { lc: "https://leetcode.com/problems/search-a-2d-matrix-ii/", gfg: "https://www.geeksforgeeks.org/problems/search-in-a-matrix17201720/1" },
  "Kth Smallest Element in a Sorted Matrix": { lc: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", gfg: "https://www.geeksforgeeks.org/problems/kth-element-in-matrix/1" },
  "Find a Peak Element II": { lc: "https://leetcode.com/problems/find-a-peak-element-ii/", gfg: "https://www.geeksforgeeks.org/explore?search=find+peak+element+2d" },
  "Peak Index in a Mountain Array": { lc: "https://leetcode.com/problems/peak-index-in-a-mountain-array/", gfg: "https://www.geeksforgeeks.org/problems/find-the-peak-element/1" },
  "Find in Mountain Array": { lc: "https://leetcode.com/problems/find-in-mountain-array/", gfg: "https://www.geeksforgeeks.org/explore?search=find+in+mountain+array" },
  "Kth Element of Two Sorted Arrays": { lc: "https://leetcode.com/search/?q=kth+element+two+sorted+arrays", gfg: "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1" },
  "Find K Closest Elements": { lc: "https://leetcode.com/problems/find-k-closest-elements/", gfg: "https://www.geeksforgeeks.org/problems/k-closest-elements3619/1" },
  "Heaters": { lc: "https://leetcode.com/problems/heaters/", gfg: "https://www.geeksforgeeks.org/explore?search=heaters" },
  "Search in Infinite Sorted Array": { lc: "https://leetcode.com/search/?q=search+in+infinite+sorted+array", gfg: "https://www.geeksforgeeks.org/problems/search-in-an-infinite-sorted-array/1" },

  // Linked List
  "Reverse Linked List": { lc: "https://leetcode.com/problems/reverse-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1" },
  "Reverse Linked List II (range)": { lc: "https://leetcode.com/problems/reverse-linked-list-ii/", gfg: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list/1" },
  "Reverse Nodes in k-Group": { lc: "https://leetcode.com/problems/reverse-nodes-in-k-group/", gfg: "https://www.geeksforgeeks.org/problems/reverse-a-linked-list-in-groups-of-given-size/1" },
  "Swap Nodes in Pairs": { lc: "https://leetcode.com/problems/swap-nodes-in-pairs/", gfg: "https://www.geeksforgeeks.org/problems/pairwise-swap-elements-of-a-linked-list-by-swapping-data/1" },
  "Palindrome Linked List": { lc: "https://leetcode.com/problems/palindrome-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1" },
  "Middle of the Linked List": { lc: "https://leetcode.com/problems/middle-of-the-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1" },
  "Linked List Cycle I & II": { lc: "https://leetcode.com/problems/linked-list-cycle/", gfg: "https://www.geeksforgeeks.org/problems/detect-loop-in-linked-list/1" },
  "Remove Nth Node From End": { lc: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", gfg: "https://www.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1" },
  "Merge Two Sorted Lists": { lc: "https://leetcode.com/problems/merge-two-sorted-lists/", gfg: "https://www.geeksforgeeks.org/problems/merge-two-sorted-linked-lists/1" },
  "Remove Duplicates from Sorted List": { lc: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/", gfg: "https://www.geeksforgeeks.org/problems/remove-duplicate-element-from-sorted-linked-list/1" },
  "Merge K Sorted Lists": { lc: "https://leetcode.com/problems/merge-k-sorted-lists/", gfg: "https://www.geeksforgeeks.org/problems/merge-k-sorted-linked-lists/1" },
  "Sort List": { lc: "https://leetcode.com/problems/sort-list/", gfg: "https://www.geeksforgeeks.org/problems/sort-a-linked-list/1" },
  "Insertion Sort List": { lc: "https://leetcode.com/problems/insertion-sort-list/", gfg: "https://www.geeksforgeeks.org/problems/insertion-sort-for-singly-linked-list/1" },
  "Partition List": { lc: "https://leetcode.com/problems/partition-list/", gfg: "https://www.geeksforgeeks.org/problems/partition-a-linked-list-around-a-given-value/1" },
  "Convert Sorted List to BST": { lc: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/sorted-linked-list-to-bst/1" },
  "Reorder List": { lc: "https://leetcode.com/problems/reorder-list/", gfg: "https://www.geeksforgeeks.org/problems/reorder-list/1" },
  "Rotate List": { lc: "https://leetcode.com/problems/rotate-list/", gfg: "https://www.geeksforgeeks.org/problems/rotate-a-linked-list/1" },
  "Odd Even Linked List": { lc: "https://leetcode.com/problems/odd-even-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/segregate-even-and-odd-nodes-in-a-linked-list5035/1" },
  "Copy List with Random Pointer": { lc: "https://leetcode.com/problems/copy-list-with-random-pointer/", gfg: "https://www.geeksforgeeks.org/problems/clone-a-linked-list-with-next-and-random-pointer/1" },
  "Flatten a Multilevel Doubly Linked List": { lc: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1" },
  "Add Two Numbers I & II": { lc: "https://leetcode.com/problems/add-two-numbers/", gfg: "https://www.geeksforgeeks.org/problems/add-two-numbers-represented-by-linked-lists/1" },

  // Stack
  "Next Greater Element I": { lc: "https://leetcode.com/problems/next-greater-element-i/", gfg: "https://www.geeksforgeeks.org/problems/next-larger-element-1587115620/1" },
  "Next Greater Element II (circular)": { lc: "https://leetcode.com/problems/next-greater-element-ii/", gfg: "https://www.geeksforgeeks.org/problems/next-greater-element/1" },
  "Daily Temperatures": { lc: "https://leetcode.com/problems/daily-temperatures/", gfg: "https://www.geeksforgeeks.org/explore?search=daily+temperatures" },
  "Online Stock Span": { lc: "https://leetcode.com/problems/online-stock-span/", gfg: "https://www.geeksforgeeks.org/explore?search=online+stock+span" },
  "Number of Visible People in Queue": { lc: "https://leetcode.com/problems/number-of-visible-people-in-a-queue/", gfg: "https://www.geeksforgeeks.org/explore?search=visible+people+queue" },
  "Sum of Subarray Minimums": { lc: "https://leetcode.com/problems/sum-of-subarray-minimums/", gfg: "https://www.geeksforgeeks.org/problems/sum-of-subarray-minimum/1" },
  "Sum of Subarray Ranges": { lc: "https://leetcode.com/problems/sum-of-subarray-ranges/", gfg: "https://www.geeksforgeeks.org/explore?search=sum+subarray+ranges" },
  "Previous Smaller Element": { lc: "https://leetcode.com/search/?q=previous+smaller+element", gfg: "https://www.geeksforgeeks.org/problems/prev-smaller-element/1" },
  "Next Smaller Element": { lc: "https://leetcode.com/search/?q=next+smaller+element", gfg: "https://www.geeksforgeeks.org/problems/next-smaller-element/1" },
  "Largest Rectangle in Histogram": { lc: "https://leetcode.com/problems/largest-rectangle-in-histogram/", gfg: "https://www.geeksforgeeks.org/problems/maximum-rectangular-area-in-a-histogram-1587115620/1" },
  "Remove K Digits (smallest number)": { lc: "https://leetcode.com/problems/remove-k-digits/", gfg: "https://www.geeksforgeeks.org/problems/remove-k-digits/1" },
  "132 Pattern": { lc: "https://leetcode.com/problems/132-pattern/", gfg: "https://www.geeksforgeeks.org/problems/132-pattern3614/1" },
  "Maximum Width Ramp": { lc: "https://leetcode.com/problems/maximum-width-ramp/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+width+ramp" },
  "Valid Parentheses": { lc: "https://leetcode.com/problems/valid-parentheses/", gfg: "https://www.geeksforgeeks.org/problems/parenthesis-checker2744/1" },
  "Minimum Remove to Make Valid": { lc: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/", gfg: "https://www.geeksforgeeks.org/problems/minimum-cost-to-make-string-valid3232/1" },
  "Minimum Add to Make Valid": { lc: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/", gfg: "https://www.geeksforgeeks.org/problems/minimum-cost-to-make-string-valid3232/1" },
  "Longest Valid Parentheses": { lc: "https://leetcode.com/problems/longest-valid-parentheses/", gfg: "https://www.geeksforgeeks.org/problems/longest-valid-parentheses5657/1" },
  "Score of Parentheses": { lc: "https://leetcode.com/problems/score-of-parentheses/", gfg: "https://www.geeksforgeeks.org/explore?search=score+of+parentheses" },
  "Remove Outermost Parentheses": { lc: "https://leetcode.com/problems/remove-outermost-parentheses/", gfg: "https://www.geeksforgeeks.org/explore?search=remove+outermost+parentheses" },
  "Check if Word is Valid (after substitutions)": { lc: "https://leetcode.com/problems/check-if-word-is-valid-after-substitutions/", gfg: "https://www.geeksforgeeks.org/explore?search=check+word+valid+substitutions" },
  "Decode String (k[encoded])": { lc: "https://leetcode.com/problems/decode-string/", gfg: "https://www.geeksforgeeks.org/problems/decode-the-string2444/1" },
  "Basic Calculator I (+, -, parentheses)": { lc: "https://leetcode.com/problems/basic-calculator/", gfg: "https://www.geeksforgeeks.org/explore?search=basic+calculator" },
  "Basic Calculator II (+, -, *, /)": { lc: "https://leetcode.com/problems/basic-calculator-ii/", gfg: "https://www.geeksforgeeks.org/problems/evaluation-of-postfix-expression1735/1" },
  "Basic Calculator III (all ops + parens)": { lc: "https://leetcode.com/problems/basic-calculator-iii/", gfg: "https://www.geeksforgeeks.org/explore?search=basic+calculator" },
  "Evaluate Reverse Polish Notation": { lc: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", gfg: "https://www.geeksforgeeks.org/problems/evaluation-of-postfix-expression1735/1" },
  "Infix to Postfix (Shunting Yard)": { lc: "https://leetcode.com/search/?q=infix+to+postfix", gfg: "https://www.geeksforgeeks.org/problems/infix-to-postfix-1587115620/1" },
  "Mini Parser (deserialize)": { lc: "https://leetcode.com/problems/mini-parser/", gfg: "https://www.geeksforgeeks.org/explore?search=mini+parser" },
  "Ternary Expression Parser": { lc: "https://leetcode.com/problems/ternary-expression-parser/", gfg: "https://www.geeksforgeeks.org/problems/parse-a-ternary-expression/1" },
  "Maximal Rectangle (2D matrix)": { lc: "https://leetcode.com/problems/maximal-rectangle/", gfg: "https://www.geeksforgeeks.org/problems/max-rectangle/1" },
  "Maximum Score of a Good Subarray": { lc: "https://leetcode.com/problems/maximum-score-of-a-good-subarray/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+score+good+subarray" },
  "Sliding Window Maximum": { lc: "https://leetcode.com/problems/sliding-window-maximum/", gfg: "https://www.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k3101/1" },
  "Sliding Window Minimum": { lc: "https://leetcode.com/search/?q=sliding+window+minimum", gfg: "https://www.geeksforgeeks.org/problems/minimum-of-all-sub-arrays-of-size-k/1" },
  "Shortest Subarray with Sum ≥ K": { lc: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", gfg: "https://www.geeksforgeeks.org/explore?search=shortest+subarray+sum+at+least+k" },
  "Jump Game VI (max score path)": { lc: "https://leetcode.com/problems/jump-game-vi/", gfg: "https://www.geeksforgeeks.org/explore?search=jump+game+vi" },
  "Maximum of Min for Every Window Size": { lc: "https://leetcode.com/search/?q=maximum+of+minimum+every+window", gfg: "https://www.geeksforgeeks.org/problems/maximum-of-minimum-for-every-window-size3453/1" },
  "Constrained Subsequence Sum": { lc: "https://leetcode.com/problems/constrained-subsequence-sum/", gfg: "https://www.geeksforgeeks.org/explore?search=constrained+subsequence+sum" },
  "Min Stack (O(1) getMin)": { lc: "https://leetcode.com/problems/min-stack/", gfg: "https://www.geeksforgeeks.org/problems/get-minimum-element-from-stack/1" },
  "Max Stack (O(1) getMax)": { lc: "https://leetcode.com/problems/max-stack/", gfg: "https://www.geeksforgeeks.org/explore?search=max+stack" },
  "Implement Queue using Stacks": { lc: "https://leetcode.com/problems/implement-queue-using-stacks/", gfg: "https://www.geeksforgeeks.org/problems/queue-using-two-stacks/1" },
  "Implement Stack using Queues": { lc: "https://leetcode.com/problems/implement-stack-using-queues/", gfg: "https://www.geeksforgeeks.org/problems/stack-using-two-queues/1" },
  "LRU Cache (Stack behavior)": { lc: "https://leetcode.com/problems/lru-cache/", gfg: "https://www.geeksforgeeks.org/problems/lru-cache/1" },
  "Dinner Plate Stacks": { lc: "https://leetcode.com/problems/dinner-plate-stacks/", gfg: "https://www.geeksforgeeks.org/explore?search=dinner+plate+stacks" },
  "Flatten Nested List Iterator": { lc: "https://leetcode.com/problems/flatten-nested-list-iterator/", gfg: "https://www.geeksforgeeks.org/explore?search=flatten+nested+list+iterator" },
  "Binary Tree Inorder (iterative)": { lc: "https://leetcode.com/problems/binary-tree-inorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/inorder-traversal-iterative/1" },
  "Binary Tree Preorder (iterative)": { lc: "https://leetcode.com/problems/binary-tree-preorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/preorder-traversal-iterative/1" },
  "Binary Tree Postorder (iterative)": { lc: "https://leetcode.com/problems/binary-tree-postorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/postorder-traversal-iterative/1" },
  "Binary Search Tree Iterator": { lc: "https://leetcode.com/problems/binary-search-tree-iterator/", gfg: "https://www.geeksforgeeks.org/problems/bst-iterator/1" },
  "Path Sum II (root to leaf paths)": { lc: "https://leetcode.com/problems/path-sum-ii/", gfg: "https://www.geeksforgeeks.org/problems/root-to-leaf-paths-sum/1" },
  "Graph DFS (iterative)": { lc: "https://leetcode.com/search/?q=graph+dfs", gfg: "https://www.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1" },
  "Number of Islands (iterative DFS)": { lc: "https://leetcode.com/problems/number-of-islands/", gfg: "https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1" },
  "Recover BST (iterative inorder)": { lc: "https://leetcode.com/problems/recover-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/fixed-two-nodes-of-a-bst/1" },

  // Tree
  "Inorder / Preorder / Postorder Traversal": { lc: "https://leetcode.com/problems/binary-tree-inorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/tree-traversal/1" },
  "Maximum Depth of Binary Tree": { lc: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/height-of-binary-tree/1" },
  "Same Tree": { lc: "https://leetcode.com/problems/same-tree/", gfg: "https://www.geeksforgeeks.org/problems/determine-if-two-trees-are-identical/1" },
  "Symmetric Tree (mirror)": { lc: "https://leetcode.com/problems/symmetric-tree/", gfg: "https://www.geeksforgeeks.org/problems/symmetric-tree/1" },
  "Invert Binary Tree": { lc: "https://leetcode.com/problems/invert-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/mirror-tree/1" },
  "Balanced Binary Tree": { lc: "https://leetcode.com/problems/balanced-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/check-for-balanced-tree/1" },
  "Diameter of Binary Tree": { lc: "https://leetcode.com/problems/diameter-of-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1" },
  "Binary Tree Tilt": { lc: "https://leetcode.com/problems/binary-tree-tilt/", gfg: "https://www.geeksforgeeks.org/explore?search=binary+tree+tilt" },
  "Longest Univalue Path": { lc: "https://leetcode.com/problems/longest-univalue-path/", gfg: "https://www.geeksforgeeks.org/problems/longest-same-value-path/1" },
  "Path Sum I & II": { lc: "https://leetcode.com/problems/path-sum/", gfg: "https://www.geeksforgeeks.org/problems/path-sum/1" },
  "Binary Tree Paths": { lc: "https://leetcode.com/problems/binary-tree-paths/", gfg: "https://www.geeksforgeeks.org/problems/root-to-leaf-paths/1" },
  "Sum Root to Leaf Numbers": { lc: "https://leetcode.com/problems/sum-root-to-leaf-numbers/", gfg: "https://www.geeksforgeeks.org/problems/root-to-leaf-paths-sum/1" },
  "Count Good Nodes in Binary Tree": { lc: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", gfg: "https://www.geeksforgeeks.org/explore?search=count+good+nodes+binary+tree" },
  "Pseudo-Palindromic Paths": { lc: "https://leetcode.com/problems/pseudo-palindromic-paths-in-a-binary-tree/", gfg: "https://www.geeksforgeeks.org/explore?search=pseudo+palindromic+paths" },
  "Validate BST": { lc: "https://leetcode.com/problems/validate-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/check-for-bst/1" },
  "Kth Smallest in BST": { lc: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", gfg: "https://www.geeksforgeeks.org/problems/find-k-th-smallest-element-in-bst/1" },
  "Lowest Common Ancestor of BST": { lc: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1" },
  "Convert Sorted Array to BST": { lc: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/array-to-bst4443/1" },
  "Recover BST": { lc: "https://leetcode.com/problems/recover-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/fixed-two-nodes-of-a-bst/1" },
  "LCA of Binary Tree": { lc: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1" },
  "LCA of BST": { lc: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", gfg: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-bst/1" },
  "LCA with Parent Pointers": { lc: "https://leetcode.com/search/?q=lowest+common+ancestor", gfg: "https://www.geeksforgeeks.org/problems/lowest-common-ancestor-in-a-binary-tree/1" },
  "Smallest Subtree with all Deepest Nodes": { lc: "https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes/", gfg: "https://www.geeksforgeeks.org/explore?search=smallest+subtree+deepest+nodes" },
  "House Robber III": { lc: "https://leetcode.com/problems/house-robber-iii/", gfg: "https://www.geeksforgeeks.org/problems/house-robber/1" },
  "Binary Tree Maximum Path Sum": { lc: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", gfg: "https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1" },
  "Binary Tree Max Path Sum": { lc: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", gfg: "https://www.geeksforgeeks.org/problems/maximum-path-sum-from-any-node/1" },
  "Binary Tree Cameras": { lc: "https://leetcode.com/problems/binary-tree-cameras/", gfg: "https://www.geeksforgeeks.org/explore?search=binary+tree+cameras" },
  "Distribute Coins in Binary Tree": { lc: "https://leetcode.com/problems/distribute-coins-in-binary-tree/", gfg: "https://www.geeksforgeeks.org/explore?search=distribute+coins+binary+tree" },
  "Serialize & Deserialize Binary Tree": { lc: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/serialize-and-deserialize-a-binary-tree/1" },
  "Construct BT from Preorder & Inorder": { lc: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/construct-tree-1/1" },
  "Construct BT from Postorder & Inorder": { lc: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/", gfg: "https://www.geeksforgeeks.org/problems/tree-from-postorder-and-inorder/1" },
  "Flatten Binary Tree to Linked List": { lc: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", gfg: "https://www.geeksforgeeks.org/problems/flatten-binary-tree-to-linked-list/1" },
  "Count Subtrees With Same Label": { lc: "https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/", gfg: "https://www.geeksforgeeks.org/explore?search=count+subtrees+same+label" },
  "Minimum Time to Collect All Apples": { lc: "https://leetcode.com/problems/minimum-time-to-collect-all-apples-in-a-tree/", gfg: "https://www.geeksforgeeks.org/explore?search=minimum+time+collect+apples" },
  "Sum of Distances in Tree (rerooting)": { lc: "https://leetcode.com/problems/sum-of-distances-in-tree/", gfg: "https://www.geeksforgeeks.org/explore?search=sum+of+distances+in+tree" },
  "Tree Diameter (from edge list)": { lc: "https://leetcode.com/search/?q=diameter+of+tree", gfg: "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1" },

  // Graph
  "Number of Islands": { lc: "https://leetcode.com/problems/number-of-islands/", gfg: "https://www.geeksforgeeks.org/problems/find-the-number-of-islands/1" },
  "Connected Components": { lc: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", gfg: "https://www.geeksforgeeks.org/problems/number-of-provinces/1" },
  "Flood Fill": { lc: "https://leetcode.com/problems/flood-fill/", gfg: "https://www.geeksforgeeks.org/problems/flood-fill-algorithm1856/1" },
  "Clone Graph": { lc: "https://leetcode.com/problems/clone-graph/", gfg: "https://www.geeksforgeeks.org/problems/clone-graph/1" },
  "01 Matrix (multi-source)": { lc: "https://leetcode.com/problems/01-matrix/", gfg: "https://www.geeksforgeeks.org/problems/distance-of-nearest-cell-having-1-1587115620/1" },
  "Surrounded Regions": { lc: "https://leetcode.com/problems/surrounded-regions/", gfg: "https://www.geeksforgeeks.org/problems/replace-os-with-xs0052/1" },
  "Word Ladder": { lc: "https://leetcode.com/problems/word-ladder/", gfg: "https://www.geeksforgeeks.org/problems/word-ladder/1" },
  "Rotting Oranges": { lc: "https://leetcode.com/problems/rotting-oranges/", gfg: "https://www.geeksforgeeks.org/problems/rotten-oranges2536/1" },
  "Cheapest Flights (K stops)": { lc: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", gfg: "https://www.geeksforgeeks.org/problems/cheapest-flights-within-k-stops/1" },
  "Network Delay Time": { lc: "https://leetcode.com/problems/network-delay-time/", gfg: "https://www.geeksforgeeks.org/explore?search=network+delay+time" },
  "Path Min Effort": { lc: "https://leetcode.com/problems/path-with-minimum-effort/", gfg: "https://www.geeksforgeeks.org/explore?search=path+minimum+effort" },
  "Swim in Rising Water": { lc: "https://leetcode.com/problems/swim-in-rising-water/", gfg: "https://www.geeksforgeeks.org/explore?search=swim+in+rising+water" },
  "Cycle in Directed Graph": { lc: "https://leetcode.com/search/?q=cycle+in+directed+graph", gfg: "https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1" },
  "Cycle in Undirected Graph": { lc: "https://leetcode.com/search/?q=cycle+in+undirected+graph", gfg: "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1" },
  "Course Schedule I": { lc: "https://leetcode.com/problems/course-schedule/", gfg: "https://www.geeksforgeeks.org/problems/course-schedule/1" },
  "Course Schedule II": { lc: "https://leetcode.com/problems/course-schedule-ii/", gfg: "https://www.geeksforgeeks.org/problems/course-schedule/1" },
  "Alien Dictionary": { lc: "https://leetcode.com/problems/alien-dictionary/", gfg: "https://www.geeksforgeeks.org/problems/alien-dictionary/1" },
  "Find Eventual Safe States": { lc: "https://leetcode.com/problems/find-eventual-safe-states/", gfg: "https://www.geeksforgeeks.org/problems/eventual-safe-states/1" },
  "Number of Provinces": { lc: "https://leetcode.com/problems/number-of-provinces/", gfg: "https://www.geeksforgeeks.org/problems/number-of-provinces/1" },
  "Redundant Connection": { lc: "https://leetcode.com/problems/redundant-connection/", gfg: "https://www.geeksforgeeks.org/problems/redundant-connection/1" },
  "Accounts Merge": { lc: "https://leetcode.com/problems/accounts-merge/", gfg: "https://www.geeksforgeeks.org/problems/accounts-merge/1" },
  "Making Large Island": { lc: "https://leetcode.com/problems/making-a-large-island/", gfg: "https://www.geeksforgeeks.org/explore?search=making+large+island" },
  "Satisfiability of Eq. Equations": { lc: "https://leetcode.com/problems/satisfiability-of-equality-equations/", gfg: "https://www.geeksforgeeks.org/explore?search=satisfiability+equality+equations" },
  "Critical Connections (Bridges)": { lc: "https://leetcode.com/problems/critical-connections-in-a-network/", gfg: "https://www.geeksforgeeks.org/problems/bridge-edge-in-graph/1" },
  "Articulation Points": { lc: "https://leetcode.com/search/?q=articulation+points", gfg: "https://www.geeksforgeeks.org/problems/articulation-point/1" },
  "Strongly Connected Components": { lc: "https://leetcode.com/search/?q=strongly+connected+components", gfg: "https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1" },
  "Number of SCCs (Kosaraju)": { lc: "https://leetcode.com/search/?q=strongly+connected+components", gfg: "https://www.geeksforgeeks.org/problems/strongly-connected-components-kosarajus-algo/1" },
  "Longest Increasing Path in Matrix": { lc: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", gfg: "https://www.geeksforgeeks.org/problems/longest-increasing-path-in-a-matrix/1" },
  "Unique Paths (grid)": { lc: "https://leetcode.com/problems/unique-paths/", gfg: "https://www.geeksforgeeks.org/problems/count-all-possible-paths-from-top-left-to-bottom-right3011/1" },
  "Number of Ways to Dest.": { lc: "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/", gfg: "https://www.geeksforgeeks.org/problems/number-of-ways-to-arrive-at-destination/1" },
  "Shortest Path Visiting All Nodes": { lc: "https://leetcode.com/problems/shortest-path-visiting-all-nodes/", gfg: "https://www.geeksforgeeks.org/explore?search=shortest+path+visiting+all+nodes" },
  "Min Cost K Edges": { lc: "https://leetcode.com/search/?q=min+cost+k+edges", gfg: "https://www.geeksforgeeks.org/explore?search=shortest+path+k+edges" },
  "Min Cost Connect All Points": { lc: "https://leetcode.com/problems/min-cost-to-connect-all-points/", gfg: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  "Classic MST": { lc: "https://leetcode.com/problems/min-cost-to-connect-all-points/", gfg: "https://www.geeksforgeeks.org/problems/minimum-spanning-tree/1" },
  "Optimize Water Distribution": { lc: "https://leetcode.com/problems/optimize-water-distribution-in-a-village/", gfg: "https://www.geeksforgeeks.org/explore?search=optimize+water+distribution" },

  // DP
  "Climbing Stairs": { lc: "https://leetcode.com/problems/climbing-stairs/", gfg: "https://www.geeksforgeeks.org/problems/count-ways-to-reach-the-nth-stair-1587115620/1" },
  "House Robber": { lc: "https://leetcode.com/problems/house-robber/", gfg: "https://www.geeksforgeeks.org/problems/house-robber/1" },
  "House Robber II (circular)": { lc: "https://leetcode.com/problems/house-robber-ii/", gfg: "https://www.geeksforgeeks.org/problems/house-robber/1" },
  "Min Cost Climbing Stairs": { lc: "https://leetcode.com/problems/min-cost-climbing-stairs/", gfg: "https://www.geeksforgeeks.org/problems/min-cost-climbing-stairs/1" },
  "Fibonacci Number": { lc: "https://leetcode.com/problems/fibonacci-number/", gfg: "https://www.geeksforgeeks.org/problems/nth-fibonacci-number1335/1" },
  "Jump Game I & II": { lc: "https://leetcode.com/problems/jump-game/", gfg: "https://www.geeksforgeeks.org/problems/jump-game/1" },
  "Decode Ways": { lc: "https://leetcode.com/problems/decode-ways/", gfg: "https://www.geeksforgeeks.org/problems/total-decoding-messages1235/1" },
  "Partition Equal Subset Sum": { lc: "https://leetcode.com/problems/partition-equal-subset-sum/", gfg: "https://www.geeksforgeeks.org/problems/subset-sum-problem2014/1" },
  "Target Sum (assign +/-)": { lc: "https://leetcode.com/problems/target-sum/", gfg: "https://www.geeksforgeeks.org/problems/target-sum-1626326450/1" },
  "Last Stone Weight II": { lc: "https://leetcode.com/problems/last-stone-weight-ii/", gfg: "https://www.geeksforgeeks.org/explore?search=last+stone+weight+ii" },
  "Coin Change (min coins)": { lc: "https://leetcode.com/problems/coin-change/", gfg: "https://www.geeksforgeeks.org/problems/number-of-coins1824/1" },
  "Coin Change II (count ways)": { lc: "https://leetcode.com/problems/coin-change-ii/", gfg: "https://www.geeksforgeeks.org/problems/coin-change2448/1" },
  "Integer Break": { lc: "https://leetcode.com/problems/integer-break/", gfg: "https://www.geeksforgeeks.org/explore?search=integer+break" },
  "Ones and Zeroes (2D knapsack)": { lc: "https://leetcode.com/problems/ones-and-zeroes/", gfg: "https://www.geeksforgeeks.org/explore?search=ones+and+zeroes" },
  "Unique Paths I & II": { lc: "https://leetcode.com/problems/unique-paths/", gfg: "https://www.geeksforgeeks.org/problems/count-all-possible-paths-from-top-left-to-bottom-right3011/1" },
  "Minimum Path Sum": { lc: "https://leetcode.com/problems/minimum-path-sum/", gfg: "https://www.geeksforgeeks.org/problems/minimum-path-sum/1" },
  "Maximal Square": { lc: "https://leetcode.com/problems/maximal-square/", gfg: "https://www.geeksforgeeks.org/problems/maximum-size-rectangle-binary-sub-matrix1213/1" },
  "Longest Common Subsequence": { lc: "https://leetcode.com/problems/longest-common-subsequence/", gfg: "https://www.geeksforgeeks.org/problems/longest-common-subsequence-1587115620/1" },
  "Longest Increasing Subsequence": { lc: "https://leetcode.com/problems/longest-increasing-subsequence/", gfg: "https://www.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1" },
  "Edit Distance": { lc: "https://leetcode.com/problems/edit-distance/", gfg: "https://www.geeksforgeeks.org/problems/edit-distance3702/1" },
  "Distinct Subsequences": { lc: "https://leetcode.com/problems/distinct-subsequences/", gfg: "https://www.geeksforgeeks.org/problems/number-of-distinct-subsequences0909/1" },
  "Longest Palindromic Substring": { lc: "https://leetcode.com/problems/longest-palindromic-substring/", gfg: "https://www.geeksforgeeks.org/problems/longest-palindrome-in-a-string3411/1" },
  "Palindromic Substrings (count)": { lc: "https://leetcode.com/problems/palindromic-substrings/", gfg: "https://www.geeksforgeeks.org/problems/count-palindrome-sub-strings-of-a-string0652/1" },
  "Longest Palindromic Subsequence": { lc: "https://leetcode.com/problems/longest-palindromic-subsequence/", gfg: "https://www.geeksforgeeks.org/problems/longest-palindromic-subsequence-1612327878/1" },
  "Word Break I & II": { lc: "https://leetcode.com/problems/word-break/", gfg: "https://www.geeksforgeeks.org/problems/word-break1352/1" },
  "Regular Expression Matching": { lc: "https://leetcode.com/problems/regular-expression-matching/", gfg: "https://www.geeksforgeeks.org/problems/regex-matching0839/1" },
  "Wildcard Matching": { lc: "https://leetcode.com/problems/wildcard-matching/", gfg: "https://www.geeksforgeeks.org/problems/wildcard-pattern-matching/1" },
  "Burst Balloons": { lc: "https://leetcode.com/problems/burst-balloons/", gfg: "https://www.geeksforgeeks.org/problems/burst-balloons3003/1" },
  "Matrix Chain Multiplication": { lc: "https://leetcode.com/search/?q=matrix+chain+multiplication", gfg: "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1" },
  "Minimum Cost to Cut a Stick": { lc: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", gfg: "https://www.geeksforgeeks.org/explore?search=minimum+cost+cut+stick" },
  "Strange Printer": { lc: "https://leetcode.com/problems/strange-printer/", gfg: "https://www.geeksforgeeks.org/explore?search=strange+printer" },
  "Travelling Salesman Problem": { lc: "https://leetcode.com/search/?q=travelling+salesman", gfg: "https://www.geeksforgeeks.org/problems/travelling-salesman-problem2732/1" },
  "Partition to K Equal Sum Subsets": { lc: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/", gfg: "https://www.geeksforgeeks.org/problems/partition-array-to-k-subsets/1" },
  "Minimum XOR Sum of Two Arrays": { lc: "https://leetcode.com/problems/minimum-xor-sum-of-two-arrays/", gfg: "https://www.geeksforgeeks.org/explore?search=minimum+xor+sum+two+arrays" },
  "Stickers to Spell Word": { lc: "https://leetcode.com/problems/stickers-to-spell-word/", gfg: "https://www.geeksforgeeks.org/explore?search=stickers+to+spell+word" },
  "Best Time to Buy/Sell Stock I": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", gfg: "https://www.geeksforgeeks.org/problems/stock-buy-and-sell-1587115621/1" },
  "Stock II (unlimited transactions)": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/", gfg: "https://www.geeksforgeeks.org/problems/stock-buy-and-sell2615/1" },
  "Stock III (at most 2 transactions)": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/", gfg: "https://www.geeksforgeeks.org/explore?search=stock+at+most+2+transactions" },
  "Stock IV (at most k transactions)": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", gfg: "https://www.geeksforgeeks.org/explore?search=stock+at+most+k+transactions" },
  "Stock with Cooldown": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", gfg: "https://www.geeksforgeeks.org/explore?search=stock+with+cooldown" },
  "Stock with Transaction Fee": { lc: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/", gfg: "https://www.geeksforgeeks.org/explore?search=stock+transaction+fee" },
  "Diameter of Binary Tree": { lc: "https://leetcode.com/problems/diameter-of-binary-tree/", gfg: "https://www.geeksforgeeks.org/problems/diameter-of-binary-tree/1" },

  // Greedy
  "Non-overlapping Intervals": { lc: "https://leetcode.com/problems/non-overlapping-intervals/", gfg: "https://www.geeksforgeeks.org/problems/non-overlapping-intervals/1" },
  "Merge Intervals": { lc: "https://leetcode.com/problems/merge-intervals/", gfg: "https://www.geeksforgeeks.org/problems/overlapping-intervals--170633/1" },
  "Meeting Rooms II": { lc: "https://leetcode.com/problems/meeting-rooms-ii/", gfg: "https://www.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1" },
  "Minimum Number of Arrows to Burst Balloons": { lc: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", gfg: "https://www.geeksforgeeks.org/explore?search=minimum+arrows+burst+balloons" },
  "Gas Station": { lc: "https://leetcode.com/problems/gas-station/", gfg: "https://www.geeksforgeeks.org/problems/circular-tour-1587115620/1" },
  "Candy": { lc: "https://leetcode.com/problems/candy/", gfg: "https://www.geeksforgeeks.org/problems/candy/1" },
  "Partition Labels": { lc: "https://leetcode.com/problems/partition-labels/", gfg: "https://www.geeksforgeeks.org/problems/partition-labels/1" },
  "Assign Cookies": { lc: "https://leetcode.com/problems/assign-cookies/", gfg: "https://www.geeksforgeeks.org/problems/assign-cookies/1" },
  "Task Scheduler": { lc: "https://leetcode.com/problems/task-scheduler/", gfg: "https://www.geeksforgeeks.org/problems/task-scheduler/1" },
  "Reorganize String": { lc: "https://leetcode.com/problems/reorganize-string/", gfg: "https://www.geeksforgeeks.org/problems/rearrange-characters4649/1" },
  "IPO": { lc: "https://leetcode.com/problems/ipo/", gfg: "https://www.geeksforgeeks.org/explore?search=ipo+maximize+capital" },
  "Maximum Performance of a Team": { lc: "https://leetcode.com/problems/maximum-performance-of-a-team/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+performance+team" },
  "Minimum Cost to Hire K Workers": { lc: "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/", gfg: "https://www.geeksforgeeks.org/explore?search=minimum+cost+hire+k+workers" },
  "Furthest Building You Can Reach": { lc: "https://leetcode.com/problems/furthest-building-you-can-reach/", gfg: "https://www.geeksforgeeks.org/explore?search=furthest+building+you+can+reach" },
  "Remove K Digits": { lc: "https://leetcode.com/problems/remove-k-digits/", gfg: "https://www.geeksforgeeks.org/problems/remove-k-digits/1" },
  "Remove Duplicate Letters": { lc: "https://leetcode.com/problems/remove-duplicate-letters/", gfg: "https://www.geeksforgeeks.org/explore?search=remove+duplicate+letters" },
  "Smallest Subsequence of Distinct Characters": { lc: "https://leetcode.com/problems/smallest-subsequence-of-distinct-characters/", gfg: "https://www.geeksforgeeks.org/explore?search=smallest+subsequence+distinct+characters" },
  "Valid Parenthesis String": { lc: "https://leetcode.com/problems/valid-parenthesis-string/", gfg: "https://www.geeksforgeeks.org/problems/valid-parenthesis-string/1" },
  "Queue Reconstruction by Height": { lc: "https://leetcode.com/problems/queue-reconstruction-by-height/", gfg: "https://www.geeksforgeeks.org/explore?search=queue+reconstruction+height" },
  "Boats to Save People": { lc: "https://leetcode.com/problems/boats-to-save-people/", gfg: "https://www.geeksforgeeks.org/explore?search=boats+to+save+people" },

  // Backtracking
  "Subsets I & II": { lc: "https://leetcode.com/problems/subsets/", gfg: "https://www.geeksforgeeks.org/problems/subsets-1613027340/1" },
  "Combination Sum I & II": { lc: "https://leetcode.com/problems/combination-sum/", gfg: "https://www.geeksforgeeks.org/problems/combination-sum-1587115620/1" },
  "Permutations I & II": { lc: "https://leetcode.com/problems/permutations/", gfg: "https://www.geeksforgeeks.org/problems/permutations-of-a-given-string-1587115620/1" },
  "Letter Combinations of a Phone Number": { lc: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", gfg: "https://www.geeksforgeeks.org/problems/possible-words-from-phone-digits-1587115620/1" },
  "Palindrome Partitioning": { lc: "https://leetcode.com/problems/palindrome-partitioning/", gfg: "https://www.geeksforgeeks.org/problems/palindrome-partitioning/1" },
  "N-Queens": { lc: "https://leetcode.com/problems/n-queens/", gfg: "https://www.geeksforgeeks.org/problems/n-queen-problem0315/1" },
  "Sudoku Solver": { lc: "https://leetcode.com/problems/sudoku-solver/", gfg: "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1" },
  "Word Search": { lc: "https://leetcode.com/problems/word-search/", gfg: "https://www.geeksforgeeks.org/problems/word-search/1" },
  "Word Search II (with Trie)": { lc: "https://leetcode.com/problems/word-search-ii/", gfg: "https://www.geeksforgeeks.org/problems/word-search/1" },
  "Restore IP Addresses": { lc: "https://leetcode.com/problems/restore-ip-addresses/", gfg: "https://www.geeksforgeeks.org/problems/generate-ip-addresses/1" },
  "Word Break II": { lc: "https://leetcode.com/problems/word-break-ii/", gfg: "https://www.geeksforgeeks.org/problems/word-break-part-23249/1" },
  "Expression Add Operators": { lc: "https://leetcode.com/problems/expression-add-operators/", gfg: "https://www.geeksforgeeks.org/explore?search=expression+add+operators" },
  "Generate Parentheses": { lc: "https://leetcode.com/problems/generate-parentheses/", gfg: "https://www.geeksforgeeks.org/problems/generate-all-possible-parentheses/1" },
  "Different Ways to Add Parentheses": { lc: "https://leetcode.com/problems/different-ways-to-add-parentheses/", gfg: "https://www.geeksforgeeks.org/explore?search=different+ways+add+parentheses" },
  "Combination Sum III": { lc: "https://leetcode.com/problems/combination-sum-iii/", gfg: "https://www.geeksforgeeks.org/explore?search=combination+sum+iii" },
  "Matchsticks to Square": { lc: "https://leetcode.com/problems/matchsticks-to-square/", gfg: "https://www.geeksforgeeks.org/explore?search=matchsticks+to+square" },
  "Beautiful Arrangement": { lc: "https://leetcode.com/problems/beautiful-arrangement/", gfg: "https://www.geeksforgeeks.org/explore?search=beautiful+arrangement" },
  "Optimal Account Balancing": { lc: "https://leetcode.com/problems/optimal-account-balancing/", gfg: "https://www.geeksforgeeks.org/explore?search=optimal+account+balancing" },
  "Shopping Offers": { lc: "https://leetcode.com/problems/shopping-offers/", gfg: "https://www.geeksforgeeks.org/explore?search=shopping+offers" },

  // Trie
  "Implement Trie (Prefix Tree)": { lc: "https://leetcode.com/problems/implement-trie-prefix-tree/", gfg: "https://www.geeksforgeeks.org/problems/trie-insert-and-search0651/1" },
  "Design Add & Search Words (wildcard)": { lc: "https://leetcode.com/problems/design-add-and-search-words-data-structure/", gfg: "https://www.geeksforgeeks.org/explore?search=design+add+search+words" },
  "Word Search II": { lc: "https://leetcode.com/problems/word-search-ii/", gfg: "https://www.geeksforgeeks.org/problems/word-search/1" },
  "Replace Words": { lc: "https://leetcode.com/problems/replace-words/", gfg: "https://www.geeksforgeeks.org/problems/replace-words/1" },
  "Maximum XOR of Two Numbers (bit-trie)": { lc: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/maximum-xor-of-two-numbers-in-an-array/1" },
  "Concatenated Words": { lc: "https://leetcode.com/problems/concatenated-words/", gfg: "https://www.geeksforgeeks.org/problems/concatenated-words/1" },
  "Word Break with Trie": { lc: "https://leetcode.com/problems/word-break/", gfg: "https://www.geeksforgeeks.org/problems/word-break1352/1" },
  "Search Suggestions System": { lc: "https://leetcode.com/problems/search-suggestions-system/", gfg: "https://www.geeksforgeeks.org/explore?search=search+suggestions+system" },
  "Maximum XOR of Two Numbers": { lc: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/maximum-xor-of-two-numbers-in-an-array/1" },
  "Maximum Genetic Difference Query": { lc: "https://leetcode.com/problems/maximum-genetic-difference-query/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+genetic+difference" },
  "Map Sum Pairs": { lc: "https://leetcode.com/problems/map-sum-pairs/", gfg: "https://www.geeksforgeeks.org/explore?search=map+sum+pairs" },
  "Design File System": { lc: "https://leetcode.com/problems/design-file-system/", gfg: "https://www.geeksforgeeks.org/explore?search=design+file+system" },
  "Design In-Memory File System": { lc: "https://leetcode.com/problems/design-in-memory-file-system/", gfg: "https://www.geeksforgeeks.org/explore?search=in+memory+file+system" },
  "Implement Magic Dictionary": { lc: "https://leetcode.com/problems/implement-magic-dictionary/", gfg: "https://www.geeksforgeeks.org/explore?search=implement+magic+dictionary" },

  // Bit Manipulation
  "Single Number": { lc: "https://leetcode.com/problems/single-number/", gfg: "https://www.geeksforgeeks.org/problems/finding-the-numbers0215/1" },
  "Single Number II & III": { lc: "https://leetcode.com/problems/single-number-ii/", gfg: "https://www.geeksforgeeks.org/problems/finding-the-numbers0215/1" },
  "Missing Number": { lc: "https://leetcode.com/problems/missing-number/", gfg: "https://www.geeksforgeeks.org/problems/missing-number-in-array1416/1" },
  "Find the Difference": { lc: "https://leetcode.com/problems/find-the-difference/", gfg: "https://www.geeksforgeeks.org/explore?search=find+the+difference" },
  "Number of 1 Bits (Hamming weight)": { lc: "https://leetcode.com/problems/number-of-1-bits/", gfg: "https://www.geeksforgeeks.org/problems/set-bits0143/1" },
  "Counting Bits": { lc: "https://leetcode.com/problems/counting-bits/", gfg: "https://www.geeksforgeeks.org/problems/number-of-1-bits/1" },
  "Reverse Bits": { lc: "https://leetcode.com/problems/reverse-bits/", gfg: "https://www.geeksforgeeks.org/problems/reverse-bits3556/1" },
  "Power of Two": { lc: "https://leetcode.com/problems/power-of-two/", gfg: "https://www.geeksforgeeks.org/problems/power-of-2-1587115620/1" },
  "Subsets (via bitmask enumeration)": { lc: "https://leetcode.com/problems/subsets/", gfg: "https://www.geeksforgeeks.org/problems/subsets-1613027340/1" },
  "Subsets": { lc: "https://leetcode.com/problems/subsets/", gfg: "https://www.geeksforgeeks.org/problems/subsets-1613027340/1" },
  "Maximum Product of Word Lengths": { lc: "https://leetcode.com/problems/maximum-product-of-word-lengths/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+product+word+lengths" },
  "Bitwise AND of Numbers Range": { lc: "https://leetcode.com/problems/bitwise-and-of-numbers-range/", gfg: "https://www.geeksforgeeks.org/problems/bitwise-and-of-range/1" },
  "Maximum XOR of Two Numbers in an Array": { lc: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/maximum-xor-of-two-numbers-in-an-array/1" },
  "Maximum XOR With an Element From Array": { lc: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/", gfg: "https://www.geeksforgeeks.org/explore?search=maximum+xor+with+element" },
  "Total Hamming Distance": { lc: "https://leetcode.com/problems/total-hamming-distance/", gfg: "https://www.geeksforgeeks.org/explore?search=total+hamming+distance" },
  "Sum of Two Integers": { lc: "https://leetcode.com/problems/sum-of-two-integers/", gfg: "https://www.geeksforgeeks.org/problems/sum-of-two-numbers-without-using-arithmetic-operators/1" },

  // Heap
  "Kth Largest Element in an Array": { lc: "https://leetcode.com/problems/kth-largest-element-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/kth-largest-element-in-bst/1" },
  "Top K Frequent Elements": { lc: "https://leetcode.com/problems/top-k-frequent-elements/", gfg: "https://www.geeksforgeeks.org/problems/top-k-frequent-elements-in-array/1" },
  "K Closest Points to Origin": { lc: "https://leetcode.com/problems/k-closest-points-to-origin/", gfg: "https://www.geeksforgeeks.org/problems/k-closest-points-to-origin/1" },
  "Find Median from Data Stream": { lc: "https://leetcode.com/problems/find-median-from-data-stream/", gfg: "https://www.geeksforgeeks.org/problems/find-median-in-a-stream-1587115620/1" },
  "Smallest Range Covering K Lists": { lc: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/", gfg: "https://www.geeksforgeeks.org/problems/find-smallest-range-containing-elements-from-k-lists/1" },
  "Sliding Window Median": { lc: "https://leetcode.com/problems/sliding-window-median/", gfg: "https://www.geeksforgeeks.org/explore?search=sliding+window+median" },
  "Find K Pairs with Smallest Sums": { lc: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/", gfg: "https://www.geeksforgeeks.org/explore?search=find+k+pairs+smallest+sums" },
  "Ugly Number II": { lc: "https://leetcode.com/problems/ugly-number-ii/", gfg: "https://www.geeksforgeeks.org/problems/ugly-numbers2254/1" },
  "Meeting Rooms III": { lc: "https://leetcode.com/problems/meeting-rooms-iii/", gfg: "https://www.geeksforgeeks.org/explore?search=meeting+rooms+iii" },
  "Employee Free Time": { lc: "https://leetcode.com/problems/employee-free-time/", gfg: "https://www.geeksforgeeks.org/explore?search=employee+free+time" },
  "Process Tasks Using Servers": { lc: "https://leetcode.com/problems/process-tasks-using-servers/", gfg: "https://www.geeksforgeeks.org/explore?search=process+tasks+using+servers" },
  "Maximize Score After K Operations": { lc: "https://leetcode.com/problems/maximize-score-after-n-operations/", gfg: "https://www.geeksforgeeks.org/explore?search=maximize+score+k+operations" },

  // Hashing
  "Two Sum": { lc: "https://leetcode.com/problems/two-sum/", gfg: "https://www.geeksforgeeks.org/problems/key-pair5616/1" },
  "Two Sum II Variant with Map": { lc: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", gfg: "https://www.geeksforgeeks.org/problems/pair-with-given-sum-in-a-sorted-array4940/1" },
  "4Sum II": { lc: "https://leetcode.com/problems/4sum-ii/", gfg: "https://www.geeksforgeeks.org/explore?search=4sum+ii" },
  "Valid Anagram": { lc: "https://leetcode.com/problems/valid-anagram/", gfg: "https://www.geeksforgeeks.org/problems/anagram-1587115620/1" },
  "Ransom Note": { lc: "https://leetcode.com/problems/ransom-note/", gfg: "https://www.geeksforgeeks.org/explore?search=ransom+note" },
  "First Unique Character in a String": { lc: "https://leetcode.com/problems/first-unique-character-in-a-string/", gfg: "https://www.geeksforgeeks.org/problems/non-repeating-character-1587115620/1" },
  "Majority Element": { lc: "https://leetcode.com/problems/majority-element/", gfg: "https://www.geeksforgeeks.org/problems/majority-element-1587115620/1" },
  "Find All Duplicates in an Array": { lc: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", gfg: "https://www.geeksforgeeks.org/problems/two-repeated-elements-1587115621/1" },
  "Sort Characters By Frequency": { lc: "https://leetcode.com/problems/sort-characters-by-frequency/", gfg: "https://www.geeksforgeeks.org/problems/sorting-characters-of-string-by-frequency/1" },
  "Contains Duplicate": { lc: "https://leetcode.com/problems/contains-duplicate/", gfg: "https://www.geeksforgeeks.org/problems/find-duplicates-in-an-array/1" },
  "Contains Duplicate II": { lc: "https://leetcode.com/problems/contains-duplicate-ii/", gfg: "https://www.geeksforgeeks.org/explore?search=contains+duplicate+ii" },
  "Contains Duplicate III": { lc: "https://leetcode.com/problems/contains-duplicate-iii/", gfg: "https://www.geeksforgeeks.org/explore?search=contains+duplicate+iii" },
  "Longest Consecutive Sequence": { lc: "https://leetcode.com/problems/longest-consecutive-sequence/", gfg: "https://www.geeksforgeeks.org/problems/longest-consecutive-subsequence2359/1" },
  "Intersection of Two Arrays": { lc: "https://leetcode.com/problems/intersection-of-two-arrays/", gfg: "https://www.geeksforgeeks.org/problems/intersection-of-two-arrays2404/1" },
  "Intersection of Two Arrays II": { lc: "https://leetcode.com/problems/intersection-of-two-arrays-ii/", gfg: "https://www.geeksforgeeks.org/problems/intersection-of-two-sorted-array-1587115620/1" },
  "Happy Number": { lc: "https://leetcode.com/problems/happy-number/", gfg: "https://www.geeksforgeeks.org/problems/happy-number/1" },
  "Jewels and Stones": { lc: "https://leetcode.com/problems/jewels-and-stones/", gfg: "https://www.geeksforgeeks.org/explore?search=jewels+and+stones" },
  "Distribute Candies": { lc: "https://leetcode.com/problems/distribute-candies/", gfg: "https://www.geeksforgeeks.org/explore?search=distribute+candies" },
  "Subarray Sums Divisible by K": { lc: "https://leetcode.com/problems/subarray-sums-divisible-by-k/", gfg: "https://www.geeksforgeeks.org/problems/subarray-with-given-sum-divisible-by-k2617/1" },
  "Contiguous Array": { lc: "https://leetcode.com/problems/contiguous-array/", gfg: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1" },
  "Find Longest Subarray with Equal 0 and 1": { lc: "https://leetcode.com/problems/contiguous-array/", gfg: "https://www.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1" },
  "Maximum Size Subarray Sum Equals K": { lc: "https://leetcode.com/search/?q=maximum+size+subarray+sum+k", gfg: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1" },
  "Count Number of Nice Subarrays": { lc: "https://leetcode.com/problems/count-number-of-nice-subarrays/", gfg: "https://www.geeksforgeeks.org/explore?search=count+nice+subarrays" },
  "Binary Subarrays With Sum": { lc: "https://leetcode.com/problems/binary-subarrays-with-sum/", gfg: "https://www.geeksforgeeks.org/explore?search=binary+subarrays+with+sum" },
  "Number of Submatrices That Sum to Target": { lc: "https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/", gfg: "https://www.geeksforgeeks.org/explore?search=submatrices+sum+target" },
  "Longest Substring Without Repeating Characters": { lc: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", gfg: "https://www.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1" },
  "Minimum Window Substring": { lc: "https://leetcode.com/problems/minimum-window-substring/", gfg: "https://www.geeksforgeeks.org/problems/smallest-window-in-a-string-containing-all-the-characters-of-another-string-1587115621/1" },
  "Longest Repeating Character Replacement": { lc: "https://leetcode.com/problems/longest-repeating-character-replacement/", gfg: "https://www.geeksforgeeks.org/explore?search=longest+repeating+character+replacement" },
  "Fruit Into Baskets": { lc: "https://leetcode.com/problems/fruit-into-baskets/", gfg: "https://www.geeksforgeeks.org/problems/fruit-into-baskets-1587115621/1" },
  "Subarrays with K Different Integers": { lc: "https://leetcode.com/problems/subarrays-with-k-different-integers/", gfg: "https://www.geeksforgeeks.org/explore?search=subarrays+k+different+integers" },
  "Count Complete Subarrays in an Array": { lc: "https://leetcode.com/problems/count-complete-subarrays-in-an-array/", gfg: "https://www.geeksforgeeks.org/explore?search=count+complete+subarrays" },
  "Group Anagrams": { lc: "https://leetcode.com/problems/group-anagrams/", gfg: "https://www.geeksforgeeks.org/problems/print-anagrams-together/1" },
  "Group Shifted Strings": { lc: "https://leetcode.com/problems/group-shifted-strings/", gfg: "https://www.geeksforgeeks.org/explore?search=group+shifted+strings" },
  "Find Duplicate File in System": { lc: "https://leetcode.com/problems/find-duplicate-file-in-system/", gfg: "https://www.geeksforgeeks.org/explore?search=find+duplicate+file+system" },
  "Encode and Decode TinyURL": { lc: "https://leetcode.com/problems/encode-and-decode-tinyurl/", gfg: "https://www.geeksforgeeks.org/explore?search=encode+decode+tinyurl" },
  "Isomorphic Strings": { lc: "https://leetcode.com/problems/isomorphic-strings/", gfg: "https://www.geeksforgeeks.org/problems/isomorphic-strings-1587115620/1" },
  "Word Pattern": { lc: "https://leetcode.com/problems/word-pattern/", gfg: "https://www.geeksforgeeks.org/explore?search=word+pattern" },
  "Valid Sudoku": { lc: "https://leetcode.com/problems/valid-sudoku/", gfg: "https://www.geeksforgeeks.org/problems/solve-the-sudoku-1587115621/1" },
  "Longest Duplicate Substring": { lc: "https://leetcode.com/problems/longest-duplicate-substring/", gfg: "https://www.geeksforgeeks.org/explore?search=longest+duplicate+substring" },
  "My Calendar I": { lc: "https://leetcode.com/problems/my-calendar-i/", gfg: "https://www.geeksforgeeks.org/explore?search=my+calendar+i" },
  "Time Based Key-Value Store": { lc: "https://leetcode.com/problems/time-based-key-value-store/", gfg: "https://www.geeksforgeeks.org/explore?search=time+based+key+value+store" },
  "Snapshot Array": { lc: "https://leetcode.com/problems/snapshot-array/", gfg: "https://www.geeksforgeeks.org/explore?search=snapshot+array" },
  "Online Election": { lc: "https://leetcode.com/problems/online-election/", gfg: "https://www.geeksforgeeks.org/explore?search=online+election" },
  "Hand of Straights": { lc: "https://leetcode.com/problems/hand-of-straights/", gfg: "https://www.geeksforgeeks.org/explore?search=hand+of+straights" },
  "Find Right Interval": { lc: "https://leetcode.com/problems/find-right-interval/", gfg: "https://www.geeksforgeeks.org/explore?search=find+right+interval" },

  // Sliding Window
  "Maximum Average Subarray I": { lc: "https://leetcode.com/problems/maximum-average-subarray-i/", gfg: "https://www.geeksforgeeks.org/problems/maximum-average-subarray/1" },
  "Find All Anagrams in a String": { lc: "https://leetcode.com/problems/find-all-anagrams-in-a-string/", gfg: "https://www.geeksforgeeks.org/problems/count-occurences-of-anagrams5839/1" },
  "Permutation in String": { lc: "https://leetcode.com/problems/permutation-in-string/", gfg: "https://www.geeksforgeeks.org/explore?search=permutation+in+string" },
  "Sliding Window Maximum (deque)": { lc: "https://leetcode.com/problems/sliding-window-maximum/", gfg: "https://www.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k3101/1" },
  "Longest Substring Without Repeating Chars": { lc: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", gfg: "https://www.geeksforgeeks.org/problems/length-of-the-longest-substring3036/1" },
  "Minimum Size Subarray Sum": { lc: "https://leetcode.com/problems/minimum-size-subarray-sum/", gfg: "https://www.geeksforgeeks.org/problems/smallest-subarray-with-sum-greater-than-x1465/1" },
  "Shortest Subarray with Sum at Least K": { lc: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", gfg: "https://www.geeksforgeeks.org/explore?search=shortest+subarray+sum+least+k" },
  "Jump Game VI": { lc: "https://leetcode.com/problems/jump-game-vi/", gfg: "https://www.geeksforgeeks.org/explore?search=jump+game+vi" },
  "Longest Continuous Subarray With Absolute Diff <= Limit": { lc: "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/", gfg: "https://www.geeksforgeeks.org/explore?search=longest+continuous+subarray+absolute+diff" },
  "Number of Substrings Containing All Three Characters": { lc: "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/", gfg: "https://www.geeksforgeeks.org/explore?search=substrings+containing+all+three+characters" },
  "Max Consecutive Ones III": { lc: "https://leetcode.com/problems/max-consecutive-ones-iii/", gfg: "https://www.geeksforgeeks.org/problems/maximize-number-of-1s0905/1" },
};

document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('.q-row').forEach(function (row) {
    var spans = Array.from(row.querySelectorAll('span'));
    var nameSpan = spans.filter(function(s) {
      return !s.classList.contains('q-num') && !s.classList.contains('tag');
    }).pop();
    if (!nameSpan) return;

    var name = nameSpan.textContent.trim();
    var entry = Q_LINKS[name];

    var lcUrl = entry ? entry.lc
      : 'https://leetcode.com/search/?q=' + encodeURIComponent(name);
    var gfgUrl = entry ? entry.gfg
      : 'https://www.geeksforgeeks.org/explore?search=' + encodeURIComponent(name);

    var badge = document.createElement('span');
    badge.className = 'q-links';
    badge.innerHTML =
      '<a class="lc-badge" href="' + lcUrl + '" target="_blank" rel="noopener">LC</a>' +
      '<a class="gfg-badge" href="' + gfgUrl + '" target="_blank" rel="noopener">GFG</a>';
    row.appendChild(badge);
  });
});
